# 项目相关配置
kit:
  # 名称
  name: Buffer'Pool
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  profile: /apps/kit/files/ # D:/kit/idea/uploadPath
  videoPath: /apps/home/video/public/ # /apps/home/video/public # /apps/kit/video D:\DeskTop\video\10-26 #
  videoDomain: http://xxx.xxx.xxx.xxx:8000/xxx
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

video:
  compress:
    to:
      frameRate: 30
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org:
      springframework: warn
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 100MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: xxx
    # 端口，默认为6379
    port: xxx #1968
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    hikari:
      configuration:
        logSql: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: xxx.xxx.xxx.xxx
    port: xxx
    username: xxx
    password: xxx

mail:
  cacheSuffix: email_code_key_
  cacheMin: 10
sms:
  apiUrl: https://xxx.xxx.xxx
  appId: xxx
  appSecret: xxx-xxx-xxx-xxx-xxx
  templateId: xxx
  timeout: 5 #min
  cacheKey: phone_code_key_

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.kit.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

map:
  baidu:
    expire: 20
    async: 5
    ak: xxx

translate:
  baidu:
    appId: xxx
    appKey: xxx
    redisKeySuffix: translate_
    expire: 20

request:
  route:
    public: /map/weather.*

mq:
  queue: test_queue
  exchange: test_exchange
  routing: my_vhost
  generator:
    maxTimes: 30
